adyma/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static

urlpatterns = [
    path('home/',views.home, name='home'),
    path('coach/', views.coach, name ='coach'),
    path('search', views.search,  name ='search'),
    
    
    
    
    
    path('activite/', views.activite, name='activite'),
    path('presence/', views.presence, name='presence'),


    #___beneficiaires

    path('inscription/', views.entretien, name='inscription'),
    #path('filtre/', views.filtre, name='filtre'),
    path('beneficiaire/', views.beneficiaire_vue, name='beneficiaire'),
    path('beneficiaire/detail/<int:pk>/', views.beneficiaire_detail, name='beneficiaire_detail'),
    path('beneficiaire/delete/<int:pk>/', views.beneficiaire_delete, name='beneficiaire_delete'),
    path('beneficiaire/update/<int:pk>/', views.beneficiaire_update, name='beneficiaire_update'),


    #___________psychosocial

    path('psychosocial/', views.psychosocial, name='psychosocial'),
    path('psychosocial_vue/', views.psychosocial_vue, name='psychosocial_vue'),
    path('psychosocial/detail/<int:id>/', views.psychosocial_detail, name='psychosocial_detail'),
    path('psychosocial/delete/<int:pk>/', views.psychosocial_delete, name='psychosocialt_delete'),
    #___________physique
    
    path('physique/', views.physique, name='physique'),
    path('physique/detail/<int:id>/', views.physique_detail, name='physique_detail'),
    path('physique/delete/<int:pk>/', views.physique_delete, name='physique_delete'),
    #path('physique/update/<int:pk>/', views.physique_update, name='physique_update'),

    #____________fiche test

    path('test/', views.test, name='test'),
    path('test/detail/<int:id>/', views.test_detail, name='test_detail'),
    path('test/delete/<int:pk>/', views.test_delete, name='test_delete'),
    path('test/update/<int:pk>/', views.test_update, name='test_update'),

    #_______etablissement
    path('etablissement/', views.etablissement, name='etablissement'),
    path('etablissement_vue/', views.etablissement_vue, name='etablissement_vue'),
    path('etablissement/detail/<int:pk>/', views.etablissement_detail, name='etablissement_detail'),
    path('etablissement/delete/<int:pk>/', views.etablissement_delete, name='etablissement_delete'),
    path('etablissement/update/<int:pk>/', views.etablissement_update, name='etablissement_update'),

    #___________groupe

    path('groupe/', views.groupe, name='groupe'),
    path('groupe_vue/', views.groupe_vue, name='groupe_vue'),
    path('groupe/delete/<int:pk>/', views.groupe_delete, name='groupe_delete'),
    path('groupe/update/<int:pk>/', views.groupe_update, name='groupe_update'),
    #__________Structurel

    path('structurel/', views.structurel, name='structurel'),


] 

adyma_prject/urls.py
from django.contrib import admin
from django.urls import path, include
from user import views as user_view
from django.contrib.auth import views as auth_views




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('adyma.urls')),
    path('register/', user_view.register, name='user_register'),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='user_login'),
    path('', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='user_logout'),
]

adyma/models.py
from django.contrib import admin
from django.db import models
from multiselectfield import *
from django.utils import timezone
from datetime import date 
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.models import User





# Register your models here.

oui_non = (
    ("1", 'oui'), ("0", 'non')
    )

adaptatibilité =(
        (1, "Espace bien adapté"),
        (0.5, "espace peu adapté"),
        (0, "Espace pas du tout adapté")
        )

nombre_activite =(
    (1,"4 et +"),
    (0.5, "Entre 2 et 4"),
    (0, "2 ou moins")
    )

salle_activite = (
    (1, "Salle bien adapté"),
    (0.5, "Salle peu adaptée"),
    (0, "Pas de salle réservée")
    )


materiel =(
    (1, "2 matériels ou +"),
    (0.5, "1 matériel"),
    (0, "Pas de matériel")
    )

lien = (
    (1, "2 ou +"),
    (0.5, "1"),
    (0, "0")
    )

externes = (
    (1, "4 ou +"),
    (0.5, "Quelques unes"),
    (0, "aucune")
    )

sorties = (
    (1 ,"2 et +"),
    (0.5, "1"),
    (0, "0")
    )
commerces = (
    (1, "3 et +"),
    (0.5, "1 ou 2"),
    (0, "0")
    )

parcs = (
    (1, "2 et +"),
    (0.5, "1"),
    (0,"0"),
    )

transport = (
    (1, "< 100 mètres"),
    (0.5, "Entre 250 et 500 mètres"),
    (0, "> 500 mètres")
    )




interet_projet = (
    ('équilibre','équilibre'),('marcher', 'marcher'),('sortir','sortir'),('rencontre','rencontre'),("bouger - m'entretenir", "bouger - m'entretenir"),('aucun intérêt', 'aucun intérêt')
    )

freins_mobilite = (
    ("peur de tomber", "peur de tomber"),
    ("perte de motivation lié à l'isolement","perte de motivation lié à l'isolement"),
    ("fatigabilité", "fatigabilité"),
    ("perte de sens et intérêt","perte de sens et intérêt"),
    ("aucun frein", "aucun frein"),
    ("douleurs", "douleurs"),
    )
theme_travail = (
    ("souplesse", "souplesse"),
    ("renforcement musculaire", "renforcement musculaire"),
    ("gestes quotidiens","gestes quotidiens"),
    ("remobilsation et reconditionnement", "remobilisation et reconditionnement"),
    ("enduance, gestion, effort", "endurance, gestion, effort"),
    ("gestion du stress","gestion du stress"),
    ("coordination", "coordination"),
    )
coll_ind =(
    ("individuel", "individuel"),("collectif","collectif")
    )



class Activite(models.Model):
    name = models.CharField(verbose_name="Nom de l'activité", max_length=100)
    descriptif = models.TextField(null = True, verbose_name="Description de l'activité")
    horaire = models.DateField(default=timezone.now, verbose_name="Horaire")

    class Meta:
        verbose_name="Activité"
        verbose_name="Activité"

    def __str__(self):
        return self.name

class Groupe(models.Model):
    nom_groupe = models.CharField(max_length=100)
    description = models.TextField( null=False, verbose_name="Description du groupe")
    activite = models.ManyToManyField(Activite, verbose_name="les Activités du groupe")
    DisplayFields =['beneficiaire']
    class Meta:
        verbose_name="Groupe au sein de l'établissement"
        verbose_name_plural = "Groupe au sein de l'établissement"

    def __str__(self):
        return self.nom_groupe


class Etablissement(models.Model):
    nom_etablissement = models.CharField(max_length=100, verbose_name="Nom de l'établissement")
    nom_directeur = models.CharField(max_length=100, verbose_name="Nom du directeur")
    adresse = models.CharField(max_length=100, verbose_name="Adresse")
    ville = models.CharField(max_length=50)
    descriptif = models.TextField(null = True, verbose_name="Description de l'établissement")
    groupe = models.ManyToManyField(Groupe, verbose_name="Groupe")
    class Meta:
        verbose_name="Etablissement"
        verbose_name_plural = "Etablissement"
        ordering = ["nom_etablissement"]

    def __str__(self):
        return self.nom_etablissement

class Structurel(models.Model):

    nom_etablissement =  models.ForeignKey(Etablissement, on_delete=models.CASCADE, verbose_name="Nom de l'etablissement")
    date = models.DateField(default=timezone.now, verbose_name="Date du diagnostique structurel")
    adaptat_env = models.FloatField(choices = adaptatibilité, verbose_name="Adaptabilité de l'environnement et de la structure à la mobilité (escaliers, barres d'appuis, luminosité...)")
    nbe_act = models.FloatField(choices = nombre_activite, verbose_name="Nombre d'activité (mémoire, gym, informatique...) par semaine proposées")
    salle_act = models.FloatField( choices = salle_activite, verbose_name="Salle d'activité réservée pour les activités physiques")
    materiel_act = models.FloatField(choices = materiel, verbose_name="Matériel d'activité physique (tapis,machines, espalier...)")
    lien_reg = models.FloatField(choices = lien, verbose_name="Liens réguliers avec organisation extérieure (centresocial, amicale...)")
    nbe_externes = models.FloatField(choices = externes, verbose_name="Nombre de personnes extérieures venant régulièrement dans l'établissement")
    sortie_sejour = models.FloatField(choices = sorties, verbose_name="Sorties et séjours organisés dans l'année")
    nbe_commerces =  models.FloatField(choices = commerces, verbose_name="Nombre de commerces de proximité (<250 mètres)")
    nbe_parc = models.FloatField(choices = parcs, verbose_name="Nombre de parcs à proximité (<500 mètres)")
    trans_commun = models.FloatField(choices = transport, verbose_name="Transports en commun à proximité")
    DisplayFields = ['Sommes de points', 'Alertes']

    class Meta():
        verbose_name="Diagnostic structurel établissement"

    def __str__(self):
        return self.nom_etablissement 
        


class Beneficiaire(models.Model):
    ok_nonok =(
    ('ok','ok'),('non ok','non ok')
    )
    coach = models.ForeignKey(User, models.CASCADE, null=True)
    residence = models.ForeignKey(Etablissement, null=True,on_delete=models.CASCADE, verbose_name="Résidence")
    date = models.DateTimeField(default=timezone.now, verbose_name="Date inscription")
    nom = models.CharField(null=True, max_length=100, verbose_name="Nom")
    prenom = models.CharField(null=True, max_length=100, verbose_name="Prenom")
    date_naissance = models.DateField(null=True, blank=True,verbose_name="Date de naissance")
    appartement = models.PositiveIntegerField(verbose_name="Numéro d'appartement")
    phone = PhoneNumberField(null=True, blank=False, verbose_name="Num. Tél.")
    maladie_path = models.CharField(max_length=300, verbose_name="Maladie/Pathologie")
    hospitalisation_année = models.PositiveIntegerField(verbose_name="Hospitalisation dans l'année")
    chute_annuel = models.PositiveSmallIntegerField(null= True, verbose_name="Chutes dans l'année")
    kiné = models.BooleanField(max_length=3)
    metre_outil = models.CharField(null=True, max_length=10, choices=ok_nonok, verbose_name="5 mètres – outils – levers de chaise")
    nb_activité_residence = models.PositiveIntegerField(verbose_name="nombre d'activitées dans la residence")
    nb_sorties_semaine = models.PositiveIntegerField(verbose_name="Nombre de sorties par semaine")
    durée_sortie_moy_minut = models.PositiveIntegerField(verbose_name="Durée des sorties en moyenne (en minutes)")
    sol_relevé = models.CharField(max_length=50 , choices=ok_nonok, verbose_name="Aller au sol et se relever")
    inte_proj = MultiSelectField(max_length=300, choices=interet_projet, verbose_name="Intérêt du projet")
    frein_mob = MultiSelectField(max_length=300, choices=freins_mobilite, verbose_name ="Freins à la mobilité")
    them_trav_souh =MultiSelectField(max_length=300, choices=theme_travail, verbose_name="Thème de travail souhaité")
    orientation = models.CharField(max_length=50, choices=coll_ind, verbose_name="Orientation")
    contractualisation = models.BooleanField(max_length=50, verbose_name="Contractualisation")
    comment = models.TextField(blank=True, null=True, verbose_name="Commentaire")
    groupe = models.ForeignKey(Groupe, null= True,on_delete=models.CASCADE)
    #Alertes = models.IntegerField(default=0, null=True)
    DisplayFields =['Age', 'Alertes']


    @property
    def Age(self):
        if(self.date_naissance != None):
            Age = date.today().year - self.date_naissance.year  
            return Age
    @property
    def Alertes(self):
        if(self.hospitalisation_année >= 1):
            Alertes =  1
        else:
            Alertes = "Pas d'alertes"
        return Alertes


    def __str__(self):
        return f'{self.nom} {self.prenom} Inscription faite par  {self.coach.username}'
    
    class Meta:
        verbose_name = "Entretien initial individuel"
        verbose_name_plural = "Entretien initial individuel"
        ordering=["nom", "prenom"]


class Test(models.Model):
    ok_nonok =(
    ('ok','ok'),('non ok','non ok')
    )
    coach = models.ForeignKey(User, models.CASCADE, null=True)
    date = models.DateTimeField(default=timezone.now, verbose_name="Date du test")
    beneficiaire = models.ForeignKey(Beneficiaire, on_delete=models.CASCADE)
    tug = models.FloatField(verbose_name="Time Up and GO", help_text='Durée en secondes')
    relev_chaise = models.PositiveIntegerField(verbose_name="Relevé de chaise par minute")
    Aller_soll = models.CharField(max_length=50 , choices=ok_nonok, verbose_name="Aller au sol")
    peri_marche = models.PositiveIntegerField(blank=True,default=0, verbose_name="Périmétrage de marche en minutes (facultatif)", help_text='durée maximale de marche estimée par la personne (durée en min / heures)')
    
    class Meta():
        verbose_name="Suivi fiche test"
        verbose_name_plural = "Suivi fiche test"

    def __str__(self):
        return f' Fiche test de {self.beneficiaire} Test passé par  {self.coach.username}' 

class Presence(models.Model):
    groupe = models.ForeignKey(Groupe, models.CASCADE, null=True, verbose_name="Groupe")
    activite =  models.ManyToManyField(Activite, verbose_name="Activité")

templates/vues/beneficiaire.html
{% extends 'partials/base.html' %}
{% block title %} Vue global des bénéficiaires {% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<h4 class="text-center text-uppercase mt-3">
     Liste des bénéficiaires 
</h4>
<hr>
<div class="container">
  <div class="row my-8">
    <div class="col"></div>
    <div class="col-md-12">
      <table class="table bg-white">
    <thead class="bg"  style="background-color: rgb(247, 172, 22);">
        <tr clas="text-white">
          <th scope="col">Résidence</th>
          <th scope="col">Noms & Prénoms</th>
          <th scope="col">Date de naissance</th>
          <th scope="col">Age</th>
          <th scope="col">Orientation</th>
          <th scope="col">Alertes</th>
          <th scope="col">coach</th>
          <th scope="col">Editer</th>
          <th scope="col">Supprimer</th>
          <th scope="col">More</th>
        </tr>
      </thead>
      <tbody>
        {% include 'vues/beneficiaire_filtre.html' %}
        {% for item in items %}
        {% if item.coach == user %}
        <tr>
         
          <td> <a  class="text text-dark" href="{% url 'beneficiaire_detail' item.id %}">{{ item.residence }}</a></td>
          
          <td><a  class="text text-dark" href="{% url 'beneficiaire_detail' item.id %}">{{ item.nom }} {{ item.prenom }}</a></td>
          <td><a  class="text text-dark" href="{% url 'beneficiaire_detail' item.id %}">{{ item.date_naissance }}</a></td>
          <td><a  class="text text-dark" href="{% url 'beneficiaire_detail' item.id %}">{{ item.Age }}</a></td>
          <td><a  class="text text-dark" href="{% url 'beneficiaire_detail' item.id %}">{{ item.orientation }}</a></td>
          <td><a  class="text text-dark" href="{% url 'beneficiaire_detail' item.id %}">{{ item.Alertes }}</a></td>
          <td><a  class="text text-dark" href="{% url 'beneficiaire_detail' item.id %}">{{ item.coach }}</a></td>
          <td>
            <a class="btn btn-outline-success btn-sm" href="{% url 'beneficiaire_update' item.id %}">editer</a>
          </td>
            <td> 
            <a class="btn btn-outline-danger btn-sm" href="{% url 'beneficiaire_delete' item.id %}">supprimer</a>
          </td> 
          <td>
            <a  class="btn btn-outline-info btn-sm" href="{% url 'beneficiaire_detail' item.id %}">Détails</a>
          </td>
        </tr>
        {% endif %}
        {% endfor %}
      </tbody>
    </table>
    </div>
  </div>
</div>



  {% endblock %}
  

templates/vues/beneficiaire_detail.html
{% extends 'partials/base.html' %}
{% block title %} Vue détaillée du bénéficiaire {% endblock %}

{% block content %}

<div class="col-md-12">
    <div class="border bg-white p-3 ">

    <div class="row mt-1">
        <div class="col-md-3">
            <p>
                <a class="btn rounded-pill bg-info" data-bs-toggle="collapse" href="{% url 'psychosocial_detail' beneficiaires.id %}"role="button" aria-expanded="false" aria-controls="collapseExample">
                    Resultat du diagnostic psychosocial
                </a>
            </p>
            <p>
                <a class="btn rounded-pill bg-info" data-bs-toggle="collapse" href="{% url 'physique_detail' beneficiaires.id %}" role="button" aria-expanded="false" aria-controls="collapseExample">
                    Resultat du diagnostic Physique  
                </a>
            </p>
            <p>
                <a class="btn rounded-pill bg-info" data-bs-toggle="collapse" href="{% url 'test_detail' beneficiaires.id %}" role="button" aria-expanded="false" aria-controls="collapseExample">
                    Resultat Fiche test
                </a>
            </p>
        </div>
        <div class="col-md-6 ">
            <div class="border bg-white p-3 ">
                <h4 class="text-center text-uppercase">Fiche d'entretien initial individuel</h4>
                <hr>
                <h4 class="text-center text-uppercase">Détails de {{ beneficiaires.nom }} {{ beneficiaires.prenom }}</h4>
                <hr>
                <table class="table bg-white table-borderless">
                   <tbody>
                        <tr>
                           <th scrop="row">Nom  </th>
                           <td>{{ beneficiaires.nom }}</td>
                       </tr>
                       <tr>
                           <th scrop="row">Prénom  </th>
                           <td>{{ beneficiaires.prenom }}</td>
                       </tr>
                       <tr>
                           <th scrop="row">Etablissement  </th>
                           <td>{{ beneficiaires.residence }}</td>
                       </tr>
                       <tr>
                           <th scrop="row">Date inscription  </th>
                           <td>{{ beneficiaires.date }}</td>
                       </tr>
                       <tr>
                           <th scrop="row">Date de naissance  </th>
                           <td>{{ beneficiaires.date_naissance }}</td>
                       </tr>
                       <tr>
                           <th scrop="row">Age  </th>
                           <hr>
                           <td>{{ beneficiaires.Age }} ans</td>
                       </tr>
                       <tr>
                           <th scrop="row">Numéro de téléphone  </th>
                           <td>{{ beneficiaires.phone }}</td>
                       </tr>
                       <tr>
                           <th scrop="row">Maladie/Pathologie  </th>
                           <td>{{ beneficiaires.maladie_path }}</td>
                       </tr>
                       <tr>
                           <th scrop="row">Hospitalisation dans l'année  </th>
                           <td>{{ beneficiaires.hospitalisation_année }}</td>
                       </tr>
                       <tr>
                           <th scrop="row">Chutes dans l'année  </th>
                           <td>{{ beneficiaires.chute_annuel }}</td>
                       </tr>
                       <tr>
                           <th scrop="row">Kiné   </th>
                           <td>{% if beneficiaires.kiné %}Oui{% else %}Non{{ beneficiaires.kiné }} {% endif %}</td>
                       </tr>
                       <tr>
                           <th scrop="row">5 mètres – outils – levers de chaise  </th>
                           <td>{{ beneficiaires.metre_outil }}</td>
                       </tr>
                       <tr>
                           <th scrop="row">Nombre de sorties par semaine  </th>
                           <td>{{ beneficiaires.nb_sorties_semaine }}</td>
                       </tr>
                       <tr>
                           <th scrop="row">Aller au sol et se relever  </th>
                           <td>{{ beneficiaires.sol_relevé }}</td>
                       </tr>
                       <tr>
                           <th scrop="row">Intérêt du projet  </th>
                           <td>{{ beneficiaires.inte_proj }}</td>
                       </tr>
                       <tr>
                           <th scrop="row">Freins à la mobilité</th>
                           <td>{{ beneficiaires.frein_mob }}</td>
                       </tr>
                       <tr>
                            <th scrop="row">Thème de travail souhaité  </th>
                            <td>{{ beneficiaires.them_trav_souh }}</td>
                        </tr> 
                       <tr>
                           <th scrop="row">Orientation  </th>
                           <td>{{ beneficiaires.orientation }}</td>
                       </tr>
                       <tr>
                           <th scrop="row">Contractualisation  </th>
                           <td>{% if beneficiaires.contractualisation %}Oui{% else %}Non{{ beneficiaires.contractualisation }}{% endif %}</td>
                       </tr>
                       <tr>
                           <th scrop="row">Commentaire  </th>
                           <td>{{ beneficiaires.comment }}</td>
                       </tr>
                       <tr>
                           <th scrop="row">Groupe  </th>
                           <td>{{ beneficiaires.groupe }}</td>
                       </tr>
                       
                   </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}

templates/vues/beneficiaire_filtre.html
 <form class="form-inline" method="get">
   {% csrf_token %}
   {{ filter.form.as_p}}
   <button class="btn btn-outlin-info " type="submit">GET IT</button>
 </form>
<ul>
    {% for beneficiaire in filter.qs  %}
    <li>
       {{ beneficiaire.residence }}
    </li>
    {% endfor %}
</ul>

templates/vues/chef_etablissement.html
<div class="container">
    <div class="row">
        <h2>Page des chefs d'établissement</h2>
    </div>
   
</div>

templates/vues/etablissement_detail.html
{% extends 'partials/base.html' %}
{% block title %} Detail de l'établissement {% endblock %}

{% block content %}

<div class="col-md-12">
    <div class="border bg-white p-3 ">
    <div class="row mt-1">
        <div class="col-md-6 offset-md-3">
            <div class="border bg-white p-3 ">
                <h4 class="text-center text-uppercase">Vue détaillée de l'établissement {{ etablissements.nom_etablissement }} </h4>
                <hr>
                <table class="table bg-white table-borderless">
                   <tbody>
                        <tr>
                           <th scrop="row">Nom de létablissement : </th>
                           <td>{{ etablissements.nom_etablissement }}</td>
                       </tr>
                       <tr>
                        <th scrop="row">Directeur / Directrice : </th>
                        <td>{{ etablissements.nom_directeur }}</td>
                    </tr> 
                       <tr>
                           <th scrop="row">Ville : </th>
                           <td>{{ etablissements.ville }}</td>
                       </tr>
                       <tr>
                           <th scrop="row">Adresse : </th>
                           <td>{{ etablissements.adresse }}</td>
                       </tr>
                       <tr>
                           <th scrop="row">Description de l'établissement : </th>
                           <td>{{ etablissements.descriptif }}</td>
                       </tr>

                       <tr>     
                           <th scrop="row">Groupe dans l'établissement :</th>
                           <td>{{ equipes }}</td>
                       </tr>
                        
                   </tbody>
                </table>
            </div>
            <div class="row mt-1">
                <div class="col">
            <p>
                    <a class="btn rounded-pill bg-info" data-bs-toggle="collapse" href="#"role="button" aria-expanded="false" aria-controls="collapseExample">
                        Diagnostic l'établissement
                    </a>
            </p>
            <p>
                    <a class="btn rounded-pill bg-info"  href="#"role="button" aria-expanded="false" aria-controls="collapseExample">
                        Tableau bilan
                    </a>
            </p>
        </div>
            </div>
    </div>
</div>

</div>

{% endblock %}

templates/vues/etablissement_vue.html
{% extends 'partials/base.html' %}
{% block title %} Vue global des bénéficiaires {% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<h4 class="text-center text-uppercase mt-3">
     Liste des établissements 
</h4>
<hr>
<div class="container">
  <div class="row my-8">
    <div class="col"></div>
    <div class="col-md-12">
      <table class="table bg-white">
    <thead class="bg" style="background-color: rgb(240, 198, 14);">
        <tr clas="text-white">
          <th scope="col">Nom de l'établissement</th>
          <th scope="col">Nom du directeur</th>
          <th scope="col">Descriptif</th><br>
          <th scope="col text-center">Editer</th>
          <th scope="col text-center">Supprimer</th>
          <th scope="col text-center">Infos</th>

          
        </tr>
      </thead>
      <tbody>
        {% for residence in residences %}
        <tr>
         
          <td> <a  class="text text-dark" href="{% url 'etablissement_detail' residence.id %}">{{ residence.nom_etablissement }}</a></td>
          <td><a  class="text text-dark" href="{% url 'etablissement_detail' residence.id %}">{{ residence.nom_directeur }}</a></td>
          <td><a  class="text text-dark" href="{% url 'etablissement_detail' residence.id %}">{{ residence.ville }}{{ residence.adresse }} </a></td>
          <td>
            <a class="btn btn-outline-info btn-sm" href="{% url 'etablissement_update' residence.id %}">Update</a></td>
            <td><a class="btn btn-outline-danger btn-sm" href="{% url 'etablissement_delete' residence.id %}">Delete</a></td>            
            <td><a  class="btn btn-outline-success btn-sm" href="{% url 'etablissement_detail' residence.id %}">More</a></td>
          
        </tr>
        {% endfor %}
      </tbody>
    </table>
    </div>
  </div>
</div>



  {% endblock %}
  

templates/vues/psychosocial_detail.html
{% extends 'partials/base.html' %}
{% block title %} detail du diagnostic psychologique {% endblock %}

{% block content %}

 {% for psycho in psychos %}
    <div class="row mt-1">
        <div class="col-md-6 offset-md-3">
            <div class="border bg-white p-3 ">
                
                <hr>
                <h4 class="text-center text-uppercase">Diagnostic psychosocial de {{ psycho.beneficiaire }}</h4>
                <hr>
                <table class="table bg-white table-borderless">
                   <tbody>
                        <tr>
                           <th scrop="row">Date du dernier diagnostic </th>
                           <td>{{ psycho.date_jour }}</td>
                       </tr>
                       <tr>
                           <th scrop="row">Nom du bénéficiaire  </th>
                           <td>{{ psycho.beneficiaire  }}</td>
                       </tr>
                       <tr>
                           <th scrop="row">Nombre de sorties par semaine  </th>
                           <td>{{ psycho.get_sorties_par_sem_display }}</td>
                       </tr>
                       <tr>
                           <th scrop="row">Alimentation  </th>
                           <td>{{ psycho.get_alimentation_display }}</td>
                       </tr>
                       <tr>
                           <th scrop="row">Nombre de chute annuel  </th>
                           <td>{{ psycho.get_chute_annuel_display }}</td>
                       </tr>
                   </tbody>
                </table>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
</div>


{% endblock %}

templates/vues/test_detail.html
{% extends 'partials/base.html' %}
{% block title %} Fiche test {% endblock %}



{% block content %}
    <div class="row mt-1">
        <div class="col-md-6 offset-md-3">
            <div class="border bg-white p-3 ">
                {% for teste in testes %}
                <hr>
                <h4 class="text-center text-uppercase">Fiche Test de {{ teste.beneficiaire.nom }} {{ teste.beneficiaire.prenom }}</h4>
                <hr>
                <table class="table bg-white table-borderless">
                    <tbody>
                        <tr>
                            <th scrop="row">Test fait par: </th>
                            <td>{{ teste.user.username }}</td>
                        </tr>
                         <tr>
                            <th scrop="row">Date du dernier diagnostic : </th>
                            <td>{{ teste.date }}</td>
                        </tr>
                        <tr>
                            <th scrop="row">Nom du bénéficiaire : </th>
                            <td>{{ teste.beneficiaire.nom }} {{ teste.beneficiaire.prenom }}</td>
                        </tr>
                        <tr>
                            <th scrop="row">Time up to go (TUG) : </th>
                            <td>{{ teste.tug }}</td>
                        </tr>
                        <tr>
                            <th scrop="row">Relevé de chaise par minute : </th>
                            <td>{{ teste.relev_chaise }}</td>
                        </tr>
                        <tr>
                            <th scrop="row">Aller au sol : </th>
                            <td>{{ teste.get_Aller_soll_display }}</td>
                        </tr>
                        <tr>
                         <th scrop="row">Périmétrage de marche en minutes (facultatif) :</th>
                         <td>{{ teste.peri_marche }}</td>
                     </tr>
                    </tbody>
                 </table>
                
            </div>
            {% endfor %}
        </div>
    </div>
</div>
</div>
{% endblock %}